// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2OAx3eLK7opkuwpyQW3vRjMYR2__DT8M',
    appId: '1:163350649839:web:c263791553ec8cc31a341a',
    messagingSenderId: '163350649839',
    projectId: 'adotapet-e3060',
    authDomain: 'adotapet-e3060.firebaseapp.com',
    storageBucket: 'adotapet-e3060.firebasestorage.app',
    measurementId: 'G-F078EB65GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrfqtTXrmDtE4CgLinNu611gfw9-dol5Q',
    appId: '1:163350649839:android:741dbb7f85c6a93f1a341a',
    messagingSenderId: '163350649839',
    projectId: 'adotapet-e3060',
    storageBucket: 'adotapet-e3060.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDhxEg2VmMQIibtRAMgyv5g3d8NtYaSXgk',
    appId: '1:163350649839:ios:16514c81175354401a341a',
    messagingSenderId: '163350649839',
    projectId: 'adotapet-e3060',
    storageBucket: 'adotapet-e3060.firebasestorage.app',
    iosBundleId: 'com.example.projetoAdotapet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDhxEg2VmMQIibtRAMgyv5g3d8NtYaSXgk',
    appId: '1:163350649839:ios:16514c81175354401a341a',
    messagingSenderId: '163350649839',
    projectId: 'adotapet-e3060',
    storageBucket: 'adotapet-e3060.firebasestorage.app',
    iosBundleId: 'com.example.projetoAdotapet',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2OAx3eLK7opkuwpyQW3vRjMYR2__DT8M',
    appId: '1:163350649839:web:360bc0275da6aae11a341a',
    messagingSenderId: '163350649839',
    projectId: 'adotapet-e3060',
    authDomain: 'adotapet-e3060.firebaseapp.com',
    storageBucket: 'adotapet-e3060.firebasestorage.app',
    measurementId: 'G-SHT1N99SXM',
  );
}
